/* USER */
export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_GROUP_INFO = 'UPDATE_GROUP_INFO';
export const LOADDING_USER_BUTTON_STATE = 'LOADDING_USER_BUTTON_STATE';

// HEADER
export const HEADER_SUCCESS = 'HEADER_SUCCESS';
export const HEADER_FAILURE = 'HEADER_FAILURE';
export const HEADER_CATLOGS = 'HEADER_CATLOGS';
export const HEADER_CHANGE = 'HEADER_CHANGE';

// SLIDE
export const SLIDERBAR_SUCCESS = 'SLIDERBAR_SUCCESS';
export const SLIDERBAR_FAILURE = 'SLIDERBAR_FAILURE';
export const SLIDER_OPERATESTATISTICS = 'SLIDER_OPERATESTATISTICS';

// 设置导航
export const SETCURRENTSUBMENU = 'SETCURRENTSUBMENU';
export const SETCURRENTMENU = 'SETCURRENTMENU';

export const MAIN_PRIVILEGE = 'MAIN_PRIVILEGE';

// FOOTER
export const SET_FOOTER = 'SET_FOOTER';
export const FOOTER_FAILURE = 'FOOTER_FAILURE';

// ACCOUNT
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_FAILURE = 'UPDATE_FAILURE';

// CHANGEPASSWORD
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_FAILURE = 'CHANGEPASSWORD_FAILURE';

// 多语言
export const GETLANGURL_SUCCESS = 'GETLANGURL_SUCCESS';
export const GETLANGURL_FAILURE = 'GETLANGURL_FAILURE';

// 设置专属经理
export const GETCONSULTANT_SUCCESS = 'GETCONSULTANT_SUCCESS';
export const GETCONSULTANT_FAILURE = 'GETCONSULTANT_FAILURE';

// 获取国家
export const GETCOUNTRY_SUCCESS = 'GETCOUNTRY_SUCCESS';
export const GETCOUNTRY_FAILURE = 'GETCOUNTRY_FAILURE';

// 获取省份
export const GETPROVINCE_SUCCESS = 'GETPROVINCE_SUCCESS';
export const GETPROVINCE_FAILURE = 'GETPROVINCE_FAILURE';

// 获取城市
export const CITY_SUCCESS = 'CITY_SUCCESS';
export const CITY_FAILURE = 'CITY_FAILURE';

// 获取行政区
export const REGION_SUCCESS = 'REGION_SUCCESS';
export const REGION_FAILURE = 'REGION_FAILURE';

// 新增门店
export const ADDGROUP_SUCCESS = 'ADDGROUP_SUCCESS';
export const ADDGROUP_FAILURE = 'ADDGROUP_FAILURE';

// 获取货币符号
export const GETCURRENCY_SUCCESS = 'GETCURRENCY_SUCCESS';
export const GETCURRENCY_FAILURE = 'GETCURRENCY_FAILURE';

// 获取门店名称
export const GETGROUPNAME_SUCCESS = 'GETGROUPNAME_SUCCESS';
export const GETGROUPNAME_FAILURE = 'GETGROUPNAME_FAILURE';

// 设置code
export const SETCURRENTMENUCODE = 'SETCURRENTMENUCODE';

export const SETCURRENTSECONDMENU = 'SETCURRENTSECONDMENU';


// 员工账号配置
export const FECH_EMPLOYEES = 'FECH_EMPLOYEES';
// 员工分配角色
export const FECH_ROLE_LIST = 'FECH_ROLE_LIST';
export const SAVE_CURRENT_USER = 'SAVE_CURRENT_USER';
export const CLEAN_ALL_ROLE = 'CLEAN_ALL_ROLE';
export const CLEAN_CURRENT_USER = 'CLEAN_CURRENT_USER';
export const UPDATE_EMPLOYEES_CURRENT_PAGE = 'UPDATE_EMPLOYEES_CURRENT_PAGE';

// 分配角色权限
export const FECH_ALL_POWERS = 'FECH_ALL_POWERS';
export const UPDATE_CHECKED_ALL_STATE = 'UPDATE_CHECKED_ALL_STATE';
export const CLEAN_CHECKED_ALL_STATE = 'CLEAN_CHECKED_ALL_STATE';

export const GROUPNAME = 'GROUPNAME';
export const SYMBOL = 'SYMBOL';
export const DYNAMICROOMSSETERROR = 'DYNAMICROOMSSETERROR';

export const FECH_ALL_ROLES = 'FECH_ALL_ROLES';
export const SAVE_CURRENT_ROLE = 'SAVE_CURRENT_ROLE';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';

// 手机区号
export const FECH_COUNTRY_LIST = 'FECH_COUNTRY_LIST';

//国际化配置
export const GETLOCALES = 'GETLOCALES';

//优惠券批次列表
export const DISCOUNT_COUPON_BATCH_LIST_SUCCESS = 'DISCOUNT_COUPON_BATCH_LIST_SUCCESS';
export const OPTIONBUTTONS = 'OPTIONBUTTONS'; // 按钮btn
//优惠券明细列表
export const DISCOUNT_COUPON_LIST_SUCCESS = 'DISCOUNT_COUPON_LIST_SUCCESS';
//优惠券使用详情
export const DISCOUNT_COUPON_USAGE_SUCCESS = 'DISCOUNT_COUPON_USAGE_SUCCESS';
//物业
export const PUBLIC_SEARCH_DATA = "PUBLIC_SEARCH_DATA"
export const PUBLIC_SEARCH_DATA_STATE = "PUBLIC_SEARCH_DATA_STATE"
export const PUBLIC_SEARCH_PARAMS = "PUBLIC_SEARCH_PARAMS"
export const PUBLIC_SEARCH_DATA_TOTAL = "PUBLIC_SEARCH_DATA_TOTAL"
//地址查询
export const ADDRESS_SEARCH = "ADDRESS_SEARCH";
export const ADDRESS_SEARCH_INIT = "ADDRESS_SEARCH_INIT";
//拜访列表
export const VISIT_LIST = "VISIT_LIST";
export const VISIT_LIST_STATE = "VISIT_LIST_STATE";
export const VISIT_LIST_PARAMS = "VISIT_LIST_PARAMS";
export const VISIT_LIST_TOTAL = "VISIT_LIST_TOTAL";
//物业列表
export const PROPERTY_LIST = "PROPERTY_LIST";
export const PROPERTY_LIST_STATE = "PROPERTY_LIST_STATE";
export const PROPERTY_LIST_PARAMS = "PROPERTY_LIST_PARAMS";
export const PROPERTY_LIST_TOTAL = "PROPERTY_LIST_TOTAL";
//私海列表
export const PRIVATE_LIST = "PRIVATE_LIST";
export const PRIVATE_LIST_STATE = "PRIVATE_LIST_STATE";
export const PRIVATE_LIST_PARAMS = "PRIVATE_LIST_PARAMS";
export const PRIVATE_LIST_TOTAL = "PRIVATE_LIST_TOTAL"
//附加信息
export const APPEND_LIST = "APPEND_LIST"

//基础线索列表
export const BASIC_LIST = "BASIC_LIST";
export const BASIC_LIST_STATE = "BASIC_LIST_STATE";
export const BASIC_LIST_PARAMS = "BASIC_LIST_PARAMS";
export const BASIC_LIST_TOTAL = "BASIC_LIST_TOTAL";
export const BASIC_SHOWTABLE = "BASIC_SHOWTABLE";

//加盟线索列表
export const JOIN_LIST = "JOIN_LIST";
export const JOIN_LIST_STATE = "JOIN_LIST_STATE";
export const JOIN_LIST_PARAMS = "JOIN_LIST_PARAMS";
export const JOIN_LIST_TOTAL = "JOIN_LIST_TOTAL";
export const JOIN_SHOWTABLE = "JOIN_SHOWTABLE";

// 三个线索相关弹窗
export const VISIT_ENTRY_STATE = "VISIT_ENTRY_STATE";
export const VISIT_CHECK_STATE = "VISIT_CHECK_STATE";
export const CLUE_DETAIL_STATE = "CLUE_DETAIL_STATE";
export const VISIT_ENTRY_DATA = "VISIT_ENTRY_DATA";
export const VISIT_CHECK_DATA = "VISIT_CHECK_DATA";
export const CLUE_DETAIL_DATA = "CLUE_DETAIL_DATA";
export const VISIT_ENTRY_LOADING = "VISIT_ENTRY_LOADING";
export const VISIT_CHECK_LOADING = "VISIT_CHECK_LOADING";
export const CLUE_DETAIL_LOADING = "CLUE_DETAIL_LOADING";


//物业详情
export const PROPERTY_DETAIL = "PROPERTY_DETAIL";
// 基础线索&加盟线索加入人单独接口
export const ADD_STAFF = "ADD_STAFF";
// 物业评估权限
export const PROPERTY_EVALUATE_PRIVILEGE = 'PROPERTY_EVALUATE_PRIVILEGE';


// 催办发起
export const LAUNCH_DATA = "LAUNCH_DATA"
export const LAUNCH_LOADING = "LAUNCH_LOADING"
export const LAUNCH_PARAMS = "LAUNCH_PARAMS"
export const LAUNCH_TOTAL = "LAUNCH_TOTAL"

// 催办处理
export const HANDLE_DATA = "HANDLE_DATA"
export const HANDLE_LOADING = "HANDLE_LOADING"
export const HANDLE_PARAMS = "HANDLE_PARAMS"
export const HANDLE_TOTAL = "HANDLE_TOTAL"

// 催办确认
export const CONFIRM_DATA = "CONFIRM_DATA"
export const CONFIRM_LOADING = "CONFIRM_LOADING"
export const CONFIRM_PARAMS = "CONFIRM_PARAMS"
export const CONFIRM_TOTAL = "CONFIRM_TOTAL"

// 催办全部
export const TOTAL_DATA = "TOTAL_DATA"
export const TOTAL_LOADING = "TOTAL_LOADING"
export const TOTAL_PARAMS = "TOTAL_PARAMS"
export const TOTAL_TOTAL = "TOTAL_TOTAL"

// 催办弹窗
export const TASK_CREATE = "TASK_CREATE"
export const TASK_DETAIL = "TASK_DETAIL"
export const TASK_HANDLE = "TASK_HANDLE"
export const TASK_CONFIRM = "TASK_CONFIRM"
export const TASK_DETAIL_DATA = "TASK_DETAIL_DATA" //详情
// 催办用户
export const TASK_USER = "TASK_USER"

//代办
export const AGENCY_DATA = "AGENCY_DATA"
export const AGENCY_LOADING = "AGENCY_LOADING"
export const AGENCY_PARAMS = "AGENCY_PARAMS"
export const AGENCY_TOTAL = "AGENCY_TOTAL"


// 价格类型设置 
export const PRICE_LOADING_CHANGE = 'PRICE_LOADING_CHANGE';
export const PRICE_COMMON_LOADING_CHANGE = 'PRICE_COMMON_LOADING_CHANGE';
export const FETCH_PRICE_DATA = 'FETCH_PRICE_DATA';

//个人资料
export const FETCH_PERSONAL_PROFILE = "FETCH_PERSONAL_PROFILE";

// 财务设置
export const FINANCE_TAB_CHANGE = 'FINANCE_TAB_CHANGE';
export const FINANCE_CHANGE_LOADING = 'FINANCE_CHANGE_LOADING';
export const FETCH_FINANCE = 'FETCH_FINANCE';

//参数设置
export const FETCH_PARAMETERS_LOADING = 'FETCH_PARAMETERS_LOADING';
export const FETCH_PARAMETERS = 'FETCH_PARAMETERS';

//平台公告
export const FETCH_NOTICE_DATA = "FETCH_NOTICE_DATA";
export const FETCH_ATTACHMENT_DATA = "FETCH_ATTACHMENT_DATA";

//商品品牌
export const FETCH_COMMODITY_BRAND_LOADING = 'FETCH_COMMODITY_BRAND_LOADING';
export const FETCH_COMMODITY_BRAND = 'FETCH_COMMODITY_BRAND';

// 供应商设置
export const FETCH_SUPPLIER_DATA = 'FETCH_SUPPLIER_DATA';
export const FETCH_SUPPLIER_VIEW_DATA = 'FETCH_SUPPLIER_VIEW_DATA'

// 采购商设置
export const FETCH_PURCHASE_DATA = 'FETCH_PURCHASE_DATA';
export const FETCH_PURCHASE_VIEW_DATA = 'FETCH_PURCHASE_VIEW_DATA';

//商品类目
export const FETCH_COMMODITY_CATEGORY = 'FETCH_COMMODITY_CATEGORY';
export const FETCH_COMMODITY_PARENT_DATA = 'FETCH_COMMODITY_PARENT_DATA';
export const FETCH_COMMODITY_SECOND_DATA = 'FETCH_COMMODITY_SECOND_DATA';


//订单
export const FETCH_ALL_ORDER='FETCH_ALL_ORDER';
export const FETCH_ALL_ORDER_LOADING='FETCH_ALL_ORDER_LOADING';

//待分配订单
export const FETCH_WAIT_ALLOCATE_ORDER='FETCH_WAIT_ALLOCATE_ORDER';
export const FETCH_WAIT_ALLOCATE_ORDER_LOADING='FETCH_WAIT_ALLOCATE_ORDER_LOADING';
//售后服务单
export const FETCH_ALL_AFTER_SALES='FETCH_ALL_AFTER_SALES';
export const FETCH_ALL_AFTER_SALES_LOADING='FETCH_ALL_AFTER_SALES_LOADING';

//采购端设置
export const FETCH_PURCHASE_LISTSLIDE = 'FETCH_PURCHASE_LISTSLIDE';
export const FETCH_PURCHASE_HOMEPAGE = "FETCH_PURCHASE_HOMEPAGE";
export const FETCH_PURCHASE_TEMPLET = "FETCH_PURCHASE_TEMPLET";

// 商品属性
export const FETCH_ATTRIBUTE_DATA = 'FETCH_ATTRIBUTE_DATA';
//财务
export const FETCH_FINANCE_RECEIVED = 'FETCH_FINANCE_RECEIVED';
export const FETCH_FINANCE_SETTLEMENT = 'FETCH_FINANCE_SETTLEMENT';
export const FETCH_FINANCE_ALLORDERS = 'FETCH_FINANCE_ALLORDERS';

//待分配订单
export const FETCH_UNALLOT_SALES='FETCH_UNALLOT_SALES';
export const FETCH_UNALLOT_SALES_LOADING='FETCH_UNALLOT_SALES_LOADING';

// spu
export const FETCH_SPU_DATA='FETCH_SPU_DATA';
export const FETCH_SPU_EDIT_DATA='FETCH_SPU_EDIT_DATA';
export const SPU_CLEAR_DATA = 'SPU_CLEAR_DATA';
export const FETCH_SPU_VIEW_DATA = 'FETCH_SPU_VIEW_DATA';

// sku
export const FETCH_SKU_DATA='FETCH_SKU_DATA';
export const FETCH_SKU_SINGLE_DATA='FETCH_SKU_SINGLE_DATA';

//待分配订单详情
export const FETCH_UNALLOTD_SALES='FETCH_UNALLOTD_SALES';
export const FETCH_UNALLOTD_SALES_LOADING='FETCH_UNALLOTD_SALES_LOADING';

//结算页面
export const FETCH_SETTLEMENT_LIST = "FETCH_SETTLEMENT_LIST";

// 商品搜索
export const FETCH_ITEM_LIST = "FETCH_ITEM_LIST";
// 商品详情
export const FETCH_ITEM_DETAIL = 'FETCH_ITEM_DETAIL';
// 订单部分
export const FETCH_ORDER_ALLORDERS = 'FETCH_ORDER_ALLORDERS';
// 售后服务单
export const FETCH_ORDER_AFTERSALES = 'FETCH_ORDER_AFTERSALES';
//平台银行账户页面
export const PLATFORM_BANK_LISTS='PLATFORM_BANK_LISTS'


//开票信息
export const INVOICE_INFO='INVOICE_INFO'

//购物车
export const FETCH_BUYCART_LIST = "FETCH_BUYCART_LIST";

//收货地址
export const FETCH_RECEIVE_LIST="FETCH_RECEIVE_LIST"